Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
      - AssociatePublicIpAddress: 'true'
        DeviceIndex: '0'
        GroupSet: 
        - Fn::ImportValue: 'Global-SecurityGroup'
